@startuml

title <size: 24> Sơ đồ tuần tự "Đánh giá Phòng" </size>

skinparam style strictuml
skinparam SequenceMessageAlignment center

autonumber

actor "Người dùng" as U
boundary ":NavigationBar" as NB  
boundary ":MyCollectionsPage" as MCP
boundary ":ReviewPage" as RP
control ":ReviewService" as RS
database ":Database" as DB  

activate U
U -> NB: Click vào tên người dùng\n trên thanh điều hướng
activate NB
NB --> U: Hiển thị menu chức năng
U -> NB: Click vào "My Collections"
NB -> MCP: Chuyến đến trang trang "Bộ sưu tập của tôi"
deactivate NB
activate MCP
MCP --> U: Hiển thị danh sách các phòng đã đặt
U -> MCP: Click vào phòng cần đánh giá
MCP -> RP: Chuyển đến trang "Đánh giá phòng"
deactivate MCP
activate RP
RP --> U: Hiển thị trang "Đánh giá phòng"
U -> RP: Đánh giá phòng (bằng cách đánh số sao)
RP -> RS: Gửi yêu cầu đánh giá phòng
activate RS
RS -> DB: Lưu thông tin đánh giá phòng
activate DB
DB --> RS: Trả về kết quả đã lưu
deactivate DB
RS --> RP: Trả về thông tin đánh giá phòng
deactivate RS
RP --> U: Hiển thị thông báo đánh giá thành công

@enduml