@startuml

title <size: 24> Sơ đồ tuần tự "Đánh giá Phòng" </size>

skinparam style strictuml
skinparam SequenceMessageAlignment center

autonumber

actor "Người dùng" as U
boundary ":NavigationBar" as NB  
boundary ":BookingHistoryPage" as BHP
boundary ":ReviewPopup" as RP
control ":ReviewService" as RS
database ":Database" as DB  

activate U

ref over U, DB
    [Xem lịch sử đặt phòng]
end ref

activate BHP
U -> BHP: Click vào nút "Đánh giá" ở phòng cần đánh giá

BHP -> RP: Hiển thị cửa sổ popup "Đánh giá phòng"
deactivate BHP
activate RP
RP --> U: Hiển thị cửa sổ popup "Đánh giá phòng"
U -> RP: Đánh giá các tiêu chí trên thang điểm 10 và/hoặc thêm bình luận
U -> RP: Bấm nút "Gửi đánh giá"
RP -> RS: Gửi yêu cầu đánh giá phòng
activate RS
RS -> DB: Lưu thông tin đánh giá phòng
activate DB
DB --> RS: Trả về kết quả đã lưu
deactivate DB
RS --> RP: Trả về thông tin đánh giá phòng
deactivate RS
RP --> U: Hiển thị thông báo đánh giá thành công
deactivate RP

@enduml