@startuml

title <size: 24> Sơ đồ tuần tự "Sắp xếp Danh sách Khách sạn" </size>

skinparam style strictuml
skinparam SequenceMessageAlignment center

autonumber

actor "Người dùng" as U
boundary ":SearchResultPage" as SRP  
control ":RoomService" as RS
database ":Database" as DB  

ref over U, DB
    [Tìm kiếm Khách sạn]
end ref


activate U
U -> SRP: Chọn nút "Sắp xếp" trên màn hình danh sách khách sạn
activate SRP
SRP --> U: Hiển thị menu các tiêu chí sắp xếp
U -> SRP: Chọn tiêu chí sắp xếp
SRP -> RS: Gửi yêu cầu sắp xếp danh sách khách sạn
activate RS
RS -> DB: Lấy dữ liệu khách sạn từ database
activate DB
DB --> RS: Trả về dữ liệu khách sạn
deactivate DB
RS -> RS: Sắp xếp danh sách khách sạn \n theo tiêu chí đã chọn
RS -> SRP: Trả về danh sách khách sạn đã sắp xếp
deactivate RS
SRP --> U: Hiển thị danh sách khách sạn đã sắp xếp
deactivate SRP

@enduml