@startuml

title <size: 24> Sơ đồ tuần tự "Xem thông tin Phòng" </size>

skinparam style strictuml
skinparam SequenceMessageAlignment center

autonumber

actor "Người dùng" as U
boundary ":HotelDetailPage" as HDP
boundary ":RoomDetailPopup" as RDP
control ":RoomService" as RS
database ":Database" as DB  

ref over U, DB
    [Xem thông tin Khách sạn]
end ref


activate U
U -> HDP: Chọn "Xem thêm chi tiết" ở một phòng bất kỳ
activate HDP
HDP -> RS: Lấy thông tin phòng
activate RS
RS -> DB: Truy vấn thông tin phòng
activate DB
DB --> RS: Trả về thông tin phòng
deactivate DB
RS --> HDP: Trả về thông tin phòng
deactivate RS
HDP -> RDP: Mở cửa sổ popup thông tin phòng
activate RDP
RDP --> U: Hiển thị thông tin phòng
deactivate RDP
deactivate HDP

@enduml