@startuml

title <size: 24> Sơ đồ tuần tự "Thêm Phòng" </size>

skinparam style strictuml
skinparam SequenceMessageAlignment center

autonumber

actor "Quản trị viên\n Khách sạn" as A
boundary ":NavigationBar" as NB  
boundary ":MyRoomsPage" as MRP 
boundary ":AddRoomPage" as ARP 
control ":RoomManagementService" as RMS
database ":Database" as DB  

activate A
A -> NB: Click vào tên người dùng trên thanh điều hướng
activate NB
NB --> A: Hiển thị menu chức năng
A -> NB: Click vào nút "Quản lý Phòng"
NB -> MRP: Chuyển đến trang "Quản lý Phòng"
deactivate NB
activate MRP
MRP --> A: Hiển thị danh sách phòng quản lý
A -> MRP: Click vào nút "Thêm Phòng"
MRP -> ARP: Chuyển đến trang "Thêm Phòng"
deactivate MRP
activate ARP
ARP --> A: Hiển thị giao diện thêm phòng
A -> ARP: Nhập thông tin phòng cần thêm
ARP -> RMS: Gửi yêu cầu thêm phòng
activate RMS
RMS -> DB: Thêm phòng vào cơ sở dữ liệu
activate DB
DB --> RMS: Trả về kết quả thêm phòng
deactivate DB
RMS --> ARP: Trả về kết quả thêm phòng
deactivate RMS
ARP --> A: Hiển thị thông báo kết quả thêm phòng
deactivate ARP


@enduml