@startuml

title <size: 24> Sơ đồ tuần tự "Đặt phòng" </size>

skinparam style strictuml
skinparam SequenceMessageAlignment center

autonumber

actor "Người dùng" as U
boundary ":HotelDetailsPage" as HDP
boundary ":BookingPage" as BP
boundary ":BookingStatusPage" as BSP
control ":BookingService" as BS
database ":Database" as DB  

ref over U, DB
    [Xem thông tin Khách sạn]
end ref

activate U

U -> HDP: Nhấn vào nút "Đặt phòng" trên phòng cần đặt
activate HDP
HDP -> BP: Chuyển sang trang "Đặt phòng"
deactivate HDP
activate BP
BP --> U: Hiển thị trang "Đặt phòng"
U -> BP: Nhập thông tin cá nhân
U -> BP: Kiểm tra thông tin phòng cần đặt
U -> BP: Chọn phương thức thanh toán
U -> BP: Nhấn nút "Đặt phòng"
BP -> BS: Gửi yêu cầu đặt phòng
activate BS
BS -> DB: Lấy thông tin phòng
activate DB
DB --> BS: Trả về thông tin phòng
deactivate DB
BS --> BP: Trả về kết quả đặt phòng
deactivate BS
BP -> BSP: Chuyển sang trang "Tình trạng đặt phòng"
deactivate BP
activate BSP
BSP --> U: Hiển thị thông báo "Đặt phòng thành công"
deactivate HDP




@enduml