@startuml

title <size: 24> Sơ đồ tuần tự "Đổi mật khẩu" </size>

skinparam style strictuml
skinparam SequenceMessageAlignment center

autonumber

actor "Người dùng" as U
boundary ":NavigationBar" as NB  
boundary ":AccountPage" as AP  
control ":AuthenticationService" as AS
database ":Database" as DB  

activate U
U -> NB: Click vào tên người dùng trên thanh điều hướng
activate NB
NB --> U: Hiển thị menu chức năng
U -> NB: Click vào nút "Tài khoản"
NB -> AP: Chuyển đến trang "Tùy chỉnh tài khoản"
deactivate NB
activate AP
AP --> U: Hiển thị trang "Tùy chỉnh tài khoản"
U -> AP: Nhập mật khẩu mới
U -> AP: Nhập lại mật khẩu mới
U -> AP: Bấm nút "Xác nhận"
AP -> AS: Gửi yêu cầu đổi mật khẩu
activate AS
AS -> AS: Xác thực yêu cầu
AS -> DB: Lưu thông tin xuống cơ sở dữ liệu
activate DB
DB --> AS: Trả về kết quả
deactivate DB
AS --> AP: Trả về kết quả
deactivate AS
AP --> U: Hiển thị kết quả đổi mật khẩu thành công
deactivate AP


@enduml