@startuml

title <size: 24> Sơ đồ tuần tự "Quên mật khẩu" </size>

skinparam style strictuml
skinparam SequenceMessageAlignment center

autonumber

actor "Người dùng" as U
boundary ":HomePage" as HP  
boundary ":LoginPage" as LP  
boundary ":AuthenticatePage" as AP  
boundary ":ForgotPasswordPage" as FPP
boundary ":SetPasswordPage" as SP
boundary ":EmailInbox" as E  
control ":AuthenticationService" as AS

activate U
U -> HP : Click nút "Đăng nhập" trên màn hình
activate HP
HP -> LP: Chuyển hướng đến trang "Đăng nhập"
deactivate HP
activate LP
LP --> U : Hiển thị trang "Đăng nhập"

U -> LP : Nhập email
U -> LP : Click nút "Tiếp tục"
LP -> AS : Gửi yêu cầu đến hệ thống xác thực
activate AS

' Trường hợp Email hợp lệ
alt Email hợp lệ 
    AS --> LP: Trả về kết quả hợp lệ
    LP -> AP : Chuyển hướng đến trang "Xác thực"
    deactivate LP
    activate AP
    AP --> U : Hiển thị trang "Xác thực"
    U -> AP: Click nút "Xác thực bằng mật khẩu"
    AP --> U: Hiển thị màn hình xác thực mật khẩu
    U -> AP: Click nút "Quên mật khẩu"
    AP -> FPP: Chuyển hướng đến trang "Quên mật khẩu"
    deactivate AP
    activate FPP
    FPP --> U: Hiển thị trang "Quên mật khẩu"
    U -> FPP: Nhập email
    U -> FPP: Click nút "Gửi"
    FPP -> AS: Gửi yêu cầu đến hệ thống xác thực
    deactivate FPP
    AS -> E: Gửi email xác thực
    activate E
    E --> U: Hiển thị email xác thực trong hòm thư
    U -> E: Click vào link xác thực
    E --> SP: Chuyển hướng đến trang "Đặt lại mật khẩu"
    deactivate E
    activate SP
    SP --> U: Hiển thị trang "Đặt lại mật khẩu"
    U -> SP: Nhập mật khẩu
    U -> SP: Click nút "Xác nhận"
    SP -> AS: Gửi yêu cầu đến hệ thống xác thực
    AS --> SP: Trả về kết quả xác thực
    SP --> U: Hiển thị thông báo xác thực thành công
    deactivate SP

' Trường hợp Email không hợp lệ
else Email không hợp lệ
    AS --> AP: Trả về kết quả không hợp lệ
    deactivate AS
    activate AP        
    AP --> U : Hiển thị thông báo email không hợp lệ
    deactivate AP
end


@enduml